### ISSUE TITLE
How can i modify the announce url and pipe out?

### ISSUE THREAD

**Issue by taobataoma** [fent/node-torrent#30]
thx, before user download the torrent file, When I read the torrent file used `nt.read`  , I want to change the torrent object announce url, and then ,pipe the file data to response.
`      nt.read(filename, function (err, torrent) {

        if (err) {

          <some err take code>

        } else {

          var announce = torrent.metadata.announce + '/' + req.user.passkey;

          torrent.metadata.announce = announce;

          res.set('Content-Type', 'application/x-bittorrent');

          res.set('Content-Disposition', 'attachment; filename=' + req.torrent.torrent_filename);

          res.send(torrent_data);// maby torrent.pipe(res)???

        }

      });

`
I used ExpressJS to send data, How can i do? very thx!

**Comment by fent** [comment]
Look at [`Torrent#createReadStream()`](https://github.com/fent/node-torrent#torrentcreatereadstream)

    torrent.createReadStream().pipe(res);

**Comment by taobataoma** [comment]
thx，because the torrent data already is decode format, i already encode it and res.send(torrent_data), it`s work fine
