### ISSUE TITLE
Can optional parameters be added to control schema validation?

### ISSUE THREAD

**Issue by purebaba** [fent/node-torrent#37]
From Wiki,I found some fields are optional.
Consider adjusting the interface to relax validation rules?

Link: [https://wiki.theory.org/index.php/BitTorrentSpecification](https://wiki.theory.org/index.php/BitTorrentSpecification)

![image](https://user-images.githubusercontent.com/14145814/59735144-e6628500-9286-11e9-8ce7-d0a948d33179.png)

**Comment by fent** [comment]
hmm, I haven't looked at this in a while, but looking at the [schema validator](https://github.com/fent/node-torrent/blob/master/lib/schema.js), it shouldn't error if optional fields are not there

**Comment by purebaba** [comment]
Or maybe I can new a pull request, And if it will be ok, could you merge it to master?

A piece of my mind
this [read](https://github.com/fent/node-torrent/blob/master/lib/read.js) function

```
module.exports = (file, callback, validate = false) => {
    if (!callback) {
        callback = () => {};
    }
    var rs = typeof file === 'string' ? fs.createReadStream(file) : file;
    var bstream = new BStream();
    rs.pipe(bstream);

    bstream.on('error', (err) => {
        if (rs.hasOwnProperty('fd')) {
            fs.close(rs.fd);
        }
        callback(err);
    });

    bstream.on('data', (result) => {
        if (validate) {
            return schema.validate(result, callback);
        }
        callback(null, new Torrent(torrent));
    });

    return rs;
};
```

**Comment by fent** [comment]
yeah, pull requests are a welcomed :)
